import { ThemeProvider } from '@/components/JoyUI';
import { LoadingBar } from '@/components/Loading';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' suppressHydrationWarning>
      <body>
        <ToastContainer />
        <ThemeProvider>
          <LoadingBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
