on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      ref:  
        type: string
        required: true
        description: The tag or SHA to checkout.


env:
  TEST: ${{ vars.TEST }}

jobs:
  check-inputs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Echo input values
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Ref: ${{ inputs.ref }}"
      - name: Echo vars
        run: 'echo "test: $TEST"'
