name: Deploy to Dev

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: ${{ secrets.GCP_IMAGE }}
  REGION: ${{ secrets.GCP_REGION }}
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'shared-449000'
          workload_identity_provider: 'projects/728042595973/locations/global/workloadIdentityPools/github/providers/my-repo'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # - name: Configure Docker
      #   run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      # - name: Build
      #   run: docker build --platform linux/amd64 -f Dockerfile.prod -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG .

      # - name: Push
      #   run: docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG

      # - name: Deploy
      #   run: gcloud run deploy $SERVICE_NAME --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG --platform managed --region $REGION --allow-unauthenticated
