name: Deploy to Dev

on:
  push:
    branches:
      - unknown

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  IMAGE: ${{ secrets.GCP_IMAGE }}
  REGION: ${{ secrets.GCP_REGION }}
  TAG: latest

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${PROJECT_ID}
          workload_identity_provider: ${WORKLOAD_IDENTITY_PROVIDER}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      # - name: Configure Docker
      #   run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          file: Dockerfile.dev
      # - name: Deploy
      #   run: gcloud run deploy $SERVICE_NAME --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG --platform managed --region $REGION --allow-unauthenticated
