name: test

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  TEST: ${{ vars.TEST }}
  TAG: latest

jobs:
  test:
    name: Echo Test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo
        run: echo "${TEST}"
      - name: Echo
        run: echo "${TAG}"
